// NOTE: We intentionally do NOT import AgentConfig here because the
// generated type in the currently vendored SDK only exposes a narrow
// permission shape. For orchestrator agents we want to preserve the full
// YAML-style permission config (task/write/etc.) that the OpenCode server
// understands, so we keep this file structurally typed instead.

// Agent metadata (frontmatter equivalent) for orchestrator-related agents.
// The long prompt bodies live in `agents/*.md` and are loaded at runtime by
// the plugin's config hook. All fields from the original frontmatter
// (description, mode, hidden, temperature, tools, permission, etc.) are
// mirrored here so that the plugin can reconstruct the complete config
// without relying on markdown parsing. We keep the type loose enough to
// accept the full PermissionConfig surface.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type OrchestratorAgentConfig = { [key: string]: any };

// Note: path computation for orchestrator state/log directories (including
// XDG_STATE_HOME support) lives in `orchestrator-paths.ts`. This file embeds
// literal permission patterns using placeholders like
// `$XDG_STATE_HOME/opencode/orchestrator/...`; these are rewritten to actual
// absolute paths in src/index.ts alongside markdown prompt rewrites.

export const orchestratorAgents: Record<string, OrchestratorAgentConfig> = {
  "orch-planner": {
    description:
      "Orchestrator planning coordinator (refiner/spec-checker/preflight orchestrator)",
    mode: "primary",
    temperature: 0.2,
    tools: {
      bash: true,
      "preflight-cli": true,
      edit: false,
      glob: true,
      grep: true,
      list: true,
      lsp: false,
      patch: false,
      question: true,
      read: true,
      skill: false,
      todoread: false,
      todowrite: false,
      orch_todo_read: false,
      orch_todo_write: false,
      webfetch: false,
      websearch: false,
      write: true,
      task: true,
    },
    permission: {
      task: {
        "*": "deny",
        "orch-refiner": "allow",
        "orch-spec-checker": "allow",
      },
      bash: {
        "*": "deny",
        "npx opencode-orchestrator loop *": "allow",
        "opencode-orchestrator loop *": "allow",
      },
      write: {
        "*": "deny",
        "$XDG_STATE_HOME/opencode/orchestrator/*/state/command-policy.json":
          "allow",
      },
      edit: {
        "*": "deny",
      },
      patch: {
        "*": "deny",
      },
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-refiner": {
    description:
      "Requirements Refiner / spec clarifier for the multi-agent orchestrator",
    mode: "subagent",
    hidden: true,
    reasoningEffort: "high",
    temperature: 0.2,
    tools: {
      bash: false,
      edit: false,
      patch: false,
      question: true,
      read: true,
      list: true,
      glob: true,
      grep: true,
      write: true,
      task: true,
    },
    permission: {
      task: {
        "*": "deny",
        "orch-local-investigator": "allow",
        "orch-public-researcher": "allow",
      },
      bash: "deny",
      write: {
        "*": "deny",
        "$XDG_STATE_HOME/opencode/orchestrator/*/state/acceptance-index.json":
          "allow",
        "$XDG_STATE_HOME/opencode/orchestrator/*/state/spec.md": "allow",
        "$XDG_STATE_HOME/opencode/orchestrator/*/state/command-policy.json":
          "allow",
      },
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-todo-writer": {
    description:
      "Planner/Todo aggregator for the multi-agent orchestrator pipeline",
    mode: "subagent",
    hidden: true,
    temperature: 0.2,
    tools: {
      bash: false,
      edit: false,
      glob: true,
      grep: true,
      list: true,
      lsp: false,
      patch: false,
      question: false,
      read: true,
      skill: false,
      todoread: false,
      todowrite: true,
      orch_todo_read: true,
      orch_todo_write: true,
      webfetch: false,
      websearch: false,
      write: true,
    },
    permission: {
      task: "deny",
      write: {
        "*": "deny",
        "$XDG_STATE_HOME/opencode/orchestrator/*/state/todo.json": "allow",
      },
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-executor": {
    description: "Lean executor agent for multi-agent orchestrator pipeline",
    mode: "subagent",
    hidden: true,
    temperature: 0.2,
    tools: {
      bash: true,
      edit: true,
      glob: true,
      grep: true,
      list: true,
      lsp: true,
      patch: true,
      question: false,
      read: true,
      skill: true,
      task: true,
      todoread: false,
      todowrite: true,
      orch_todo_read: true,
      orch_todo_write: true,
      webfetch: true,
      websearch: true,
      write: true,
    },
    permission: {
      task: {
        "*": "deny",
        explore: "allow",
        "orch-local-investigator": "allow",
        "orch-public-researcher": "allow",
      },
      write: {
        "$XDG_STATE_HOME/opencode/orchestrator/*/artifacts/*": "allow",
      },
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-auditor": {
    description: "Strict external verifier for orchestrator runs",
    mode: "subagent",
    hidden: true,
    reasoningEffort: "high",
    temperature: 0.1,
    tools: {
      bash: true,
      edit: false,
      glob: true,
      grep: true,
      list: true,
      lsp: true,
      patch: false,
      question: false,
      read: true,
      skill: false,
      todoread: false,
      todowrite: false,
      orch_todo_read: false,
      orch_todo_write: false,
      webfetch: false,
      websearch: false,
      write: false,
    },
    permission: {
      bash: {
        "*": "ask",
        "### git read-only commands ###": "allow",
        "git status": "allow",
        "git status *": "allow",
        "git diff": "allow",
        "git diff *": "allow",
        "git show": "allow",
        "git show *": "allow",
        "git log": "allow",
        "git log *": "allow",
        "git rev-parse *": "allow",
        "git remote -v": "allow",
        "git branch": "allow",
        "git branch -v*": "allow",
        "git branch --show-current": "allow",
        "git tag": "allow",
        "git tag *": "allow",
        "git ls-files": "allow",
        "git ls-files *": "allow",
        "git cat-file *": "allow",
        "git describe *": "allow",
        "git fetch": "allow",
        "git fetch *": "allow",
        "### git dangerous commands ###": "deny",
        "git add *": "deny",
        "git commit": "deny",
        "git commit *": "deny",
        "git restore *": "deny",
        "git checkout": "deny",
        "git checkout *": "deny",
        "git switch": "deny",
        "git switch *": "deny",
        "git merge": "deny",
        "git merge *": "deny",
        "git rebase": "deny",
        "git rebase *": "deny",
        "git stash": "deny",
        "git stash *": "deny",
        "git pull": "deny",
        "git pull *": "deny",
        "git cherry-pick": "deny",
        "git cherry-pick *": "deny",
        "git revert": "deny",
        "git revert *": "deny",
        "git reset --hard": "deny",
        "git reset --hard *": "deny",
        "git clean -fd": "deny",
        "git clean -fd *": "deny",
        "git clean -fdx": "deny",
        "git clean -fdx *": "deny",
        "git filter-branch": "deny",
        "git filter-branch *": "deny",
        "git push": "deny",
        "git push *": "deny",
        "### removing files & modifying permissions ###": "deny",
        "rm *": "deny",
        "mv *": "deny",
        "chmod *": "deny",
        "chown *": "deny",
        "### manipulating stdin/stdout & investigating files ###": "allow",
        ls: "allow",
        "ls *": "allow",
        "mkdir *": "allow",
        "jq *": "allow",
        rg: "allow",
        "rg *": "allow",
        "sed -n *": "allow",
        "echo *": "allow",
        "grep *": "allow",
        "head *": "allow",
        "tail *": "allow",
        sort: "allow",
        cut: "allow",
        "cut *": "allow",
        uniq: "allow",
        "uniq *": "allow",
        tr: "allow",
        "tr *": "allow",
        nl: "allow",
        "nl *": "allow",
        "### helper commands for one-line shell scripts ###": "allow",
        true: "allow",
        "true *": "allow",
        false: "allow",
        "false *": "allow",
        command: "allow",
        "command *": "allow",
        "which *": "allow",
        test: "allow",
        "test *": "allow",
        "[": "allow",
        "[ *": "allow",
        "bash -n *": "allow",
      },
      edit: "deny",
      glob: "allow",
      grep: "allow",
      list: "allow",
      lsp: "allow",
      patch: "deny",
      task: "deny",
      question: "deny",
      read: "allow",
      todoread: "deny",
      todowrite: "deny",
      orch_todo_read: "deny",
      orch_todo_write: "deny",
      webfetch: "deny",
      websearch: "deny",
      write: "deny",
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-spec-checker": {
    description:
      "Spec and feasibility checker for the multi-agent orchestrator pipeline",
    mode: "subagent",
    hidden: true,
    reasoningEffort: "high",
    temperature: 0.1,
    tools: {
      bash: false,
      edit: false,
      glob: true,
      grep: true,
      list: true,
      lsp: false,
      patch: false,
      question: false,
      read: true,
      skill: false,
      todoread: false,
      todowrite: false,
      orch_todo_read: false,
      orch_todo_write: false,
      webfetch: false,
      websearch: false,
      write: false,
    },
    permission: {
      bash: "deny",
      edit: "deny",
      glob: "allow",
      grep: "allow",
      list: "allow",
      lsp: "deny",
      patch: "deny",
      task: "deny",
      question: "deny",
      read: "allow",
      todoread: "deny",
      todowrite: "deny",
      orch_todo_read: "deny",
      orch_todo_write: "deny",
      webfetch: "deny",
      websearch: "deny",
      write: "deny",
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-local-investigator": {
    description:
      "Local repository investigation specialist. Use this when you need to find where a function, type, config key, or file is defined and how it connects to the rest of the project. Returns absolute paths, call chains, existing patterns to follow, and uncertainties — so you can act without further exploration. Prefer this over doing broad searches yourself when the answer requires mapping multiple files or symbols.",
    mode: "subagent",
    hidden: false,
    temperature: 0.1,
    tools: {
      bash: false,
      codesearch: true,
      edit: false,
      glob: true,
      grep: true,
      list: true,
      lsp: true,
      patch: false,
      question: false,
      read: true,
      skill: false,
      task: false,
      todoread: false,
      todowrite: false,
      orch_todo_read: false,
      orch_todo_write: false,
      webfetch: false,
      websearch: false,
      write: false,
    },
    permission: {
      bash: "deny",
      edit: "deny",
      glob: "allow",
      grep: "allow",
      list: "allow",
      lsp: "allow",
      patch: "deny",
      task: "deny",
      question: "deny",
      read: "allow",
      todoread: "deny",
      todowrite: "deny",
      orch_todo_read: "deny",
      orch_todo_write: "deny",
      webfetch: "deny",
      websearch: "deny",
      write: "deny",
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-public-researcher": {
    description:
      "Public information research specialist. Use this when you need to look up facts, how-tos, or context that lives outside the codebase — library APIs, error codes, configuration options, protocol specs, version differences, known issues, or general knowledge. Returns answers with source citations so you can trust the result. Prefer this over guessing or relying on training data cutoff when freshness or accuracy matters.",
    mode: "subagent",
    hidden: false,
    temperature: 0.1,
    tools: {
      bash: false,
      codesearch: true,
      edit: false,
      glob: false,
      grep: false,
      list: false,
      lsp: false,
      patch: false,
      question: false,
      read: true,
      skill: false,
      task: false,
      todoread: false,
      todowrite: false,
      orch_todo_read: false,
      orch_todo_write: false,
      webfetch: true,
      websearch: true,
      write: false,
    },
    permission: {
      bash: "deny",
      edit: "deny",
      glob: "deny",
      grep: "deny",
      list: "deny",
      lsp: "deny",
      patch: "deny",
      task: "deny",
      question: "deny",
      read: "allow",
      todoread: "deny",
      todowrite: "deny",
      orch_todo_read: "deny",
      orch_todo_write: "deny",
      webfetch: "allow",
      websearch: "allow",
      write: "deny",
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
  "orch-preflight-runner": {
    description:
      "Preflight command availability checker for the multi-agent orchestrator",
    mode: "subagent",
    hidden: true,
    temperature: 0.2,
    tools: {
      bash: true,
      edit: false,
      glob: false,
      grep: false,
      list: false,
      lsp: false,
      patch: false,
      question: false,
      read: false,
      skill: false,
      todoread: false,
      todowrite: false,
      orch_todo_read: false,
      orch_todo_write: false,
      webfetch: false,
      websearch: false,
      write: false,
    },
    permission: {
      bash: {
        "### git 操作系統（書き込み: 拒否） ###": "deny",
        "git add *": "deny",
        "git commit": "deny",
        "git commit *": "deny",
        "git restore *": "deny",
        "git checkout": "deny",
        "git checkout *": "deny",
        "git switch": "deny",
        "git switch *": "deny",
        "git merge": "deny",
        "git merge *": "deny",
        "git rebase": "deny",
        "git rebase *": "deny",
        "git stash": "deny",
        "git stash *": "deny",
        "git pull": "deny",
        "git pull *": "deny",
        "git cherry-pick": "deny",
        "git cherry-pick *": "deny",
        "git revert": "deny",
        "git revert *": "deny",
        "git reset --hard": "deny",
        "git reset --hard *": "deny",
        "git clean -fd": "deny",
        "git clean -fd *": "deny",
        "git clean -fdx": "deny",
        "git clean -fdx *": "deny",
        "git filter-branch": "deny",
        "git filter-branch *": "deny",
        "git push": "deny",
        "git push *": "deny",
        "### ファイル削除・権限編集の禁止 ###": "deny",
        "rm *": "deny",
        "mv *": "deny",
        "chmod *": "deny",
        "chown *": "deny",
      },
      edit: "deny",
      glob: "deny",
      grep: "deny",
      list: "deny",
      lsp: "deny",
      patch: "deny",
      question: "deny",
      read: "deny",
      skill: "deny",
      task: "deny",
      todoread: "deny",
      todowrite: "deny",
      orch_todo_read: "deny",
      orch_todo_write: "deny",
      webfetch: "deny",
      websearch: "deny",
      write: "deny",
      external_directory: {
        "$XDG_STATE_HOME/opencode/orchestrator/**": "allow",
      },
    },
  },
};

export type OrchestratorAgentKey = keyof typeof orchestratorAgents;
